# Dockerfile for dev

FROM node:16-alpine

user node
run  mkdir -p /home/node/app
workdir /home/node/app
copy --chown=node:node package.json .
run  npm install

copy --chown=node:node . .




#WORKDIR '/app'

# dependencies
#COPY package.json .
#RUN  npm install

# copy rest of files
#COPY . .

# cmd
CMD ["npm", "run", "start"]




